#+TITLE: Clean NodeJs API
#+AUTHOR: Joaquim Gregório da Silva Neto
* Setting up .gitconfig
- Add these lines to your *.gitconfig* file:
  #+begin_src toml
[user]
	email = <your-email>
	name = <your-name>
[init]
	defaultBranch = main
[core]
	editor = nvim
[alias]
	s = !git status -s
	c = !git add . && git commit -m
	amend = !git add . && git commit --amend --no-edit
	l = !git log --pretty=format:'%C(blue)%h%C(red)%d %C(white)%s %C(cyan)[%cn] %C(green)%cr'
  #+end_src
- You can add the *git-commit-msg-linter* package to standarlize your commit messages. This package will raise errors when you send a non-default commit message.
* Typescript
- First install *typescript* and *@types/node* as development dependencies.
- In *tsconfig.json* file you must set *outDir*, *module*, *target*, *esModuleInterop* and *allowJs* for a basic typescript setup. You can generate the typescript config file with ~yarn tsc --init~.
* Eslint
- Here we will use the *eslint-config-google* package that comes with the following dependencies: *eslint*, *@typescript-eslint/eslint-plugin*, *@typescript-eslint/parser* and *eslint*.
- The eslint config file should look like:
  #+begin_src json
{
    "root": true,
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "@typescript-eslint"
    ],
    "parserOptions": {
        "project": "./tsconfig.json"
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "google"
    ],
    "rules": {
        "object-curly-spacing": "off"
    }
}
  #+end_src
- And the *.eslintignore* file:
  #+begin_src text
node_modules
dist
build
  #+end_src
* Husky and Lint Staged
- First install *husky* and *lint-staged* packages as development dependencies.
- They are usefull to check out files before commit them.
- *Husky* will do this main task and *Lint Staged* will only lint staged files to guarantee that we will not have slowly commits.
- .huskyrc.json:
  #+begin_src json
{
    "hooks": {
        "pre-commit": "lint-staged"
    }
}
  #+end_src
- .lintstagedrc.json:
  #+begin_src json
{
    "*.ts": [
        "eslint 'src/**' --fix",
        "git add"
    ]
}
  #+end_src
